### ISSUE TITLE
Cant get bugsnag to see sourcemaps. 

### ISSUE THREAD

**Issue by andredewaard** [stereodenis/fastlane-plugin-bugsnag_sourcemaps_upload#6] opened 2020-11-03 10:02 UTC
I keep getting the error:
```
Missing source map:Source map not found for version 0.7.5 or version code 85
Source maps upload guide
Upload your source maps to show the original source file and line numbers. (Note that events are not reprocessed after source maps are uploaded.)
```

This is how my fastfile looks like
```
platform :ios do

  desc "Push the latest testflight build to testers"
  lane :beta do
    prompt(text: 'Did you update .env.production files and update info.plist releaseStage to "production"? if no stop this build.', boolean: true)

    version = get_version_number(xcodeproj: "xxxx.xcodeproj", target: "xxxxx")
    newVersionNumber = prompt(text: "Please update version number (current version: " + version + ", eg: 2.1.1, major/minor/patch)")
    increment_version_number(version_number: newVersionNumber)

    increment_build_number

    match(type: "appstore", git_url: "xxxxx")
    build_app(workspace: "xxxxxx.xcworkspace", scheme: "xxxxxx")

    upload_to_testflight

    download_dsyms(version: newVersionNumber)
    upload_symbols_to_bugsnag(api_key: 'xxxxxxxxxxxx')
    Dir.chdir("..") do
      bugsnag_sourcemaps_upload(
        api_key: 'xxxxxxxxxxx',
        app_version: newVersionNumber
      )
    end
    clean_build_artifacts
  end

end
```

**Comment by isokolovskii** [comment] 2020-11-03 12:14
This issue is a duplicate of #7
All other discussion should be continued there. [My reply on the situation
](https://github.com/stereodenis/fastlane-plugin-bugsnag_sourcemaps_upload/issues/7#issuecomment-721079734)

@stereodenis can you please close this issue?

**Closed as completed** 2020-11-03 12:17 UTC
